/** Named tiles sliced from the vendor sheets. Index = row * 12 + column on the packed sheet. */
export const TILES: Record<string, { pack: 'tiny-farm' | 'tiny-town'; index: number }> = {
  // field
  soil: { pack: 'tiny-farm', index: 0 },
  // crops: sprout, growing, ripe, harvested item, seed bag
  'wheat-1': { pack: 'tiny-farm', index: 64 },
  'wheat-2': { pack: 'tiny-farm', index: 65 },
  'wheat-3': { pack: 'tiny-farm', index: 66 },
  wheat: { pack: 'tiny-farm', index: 68 },
  'carrot-1': { pack: 'tiny-farm', index: 4 },
  'carrot-2': { pack: 'tiny-farm', index: 5 },
  'carrot-3': { pack: 'tiny-farm', index: 6 },
  carrot: { pack: 'tiny-farm', index: 8 },
  'corn-1': { pack: 'tiny-farm', index: 28 },
  'corn-2': { pack: 'tiny-farm', index: 29 },
  'corn-3': { pack: 'tiny-farm', index: 30 },
  corn: { pack: 'tiny-farm', index: 32 },
  'tomato-1': { pack: 'tiny-farm', index: 40 },
  'tomato-2': { pack: 'tiny-farm', index: 41 },
  'tomato-3': { pack: 'tiny-farm', index: 42 },
  tomato: { pack: 'tiny-farm', index: 44 },
  'cabbage-1': { pack: 'tiny-farm', index: 52 },
  'cabbage-2': { pack: 'tiny-farm', index: 53 },
  'cabbage-3': { pack: 'tiny-farm', index: 54 },
  cabbage: { pack: 'tiny-farm', index: 56 },
  // animals and goods
  sheep: { pack: 'tiny-farm', index: 120 },
  cow: { pack: 'tiny-farm', index: 121 },
  chicken: { pack: 'tiny-farm', index: 122 },
  milk: { pack: 'tiny-farm', index: 123 },
  egg: { pack: 'tiny-farm', index: 125 },
  beehive: { pack: 'tiny-town', index: 94 },
  // people and props
  farmhand: { pack: 'tiny-farm', index: 108 },
  hay: { pack: 'tiny-farm', index: 96 },
  trough: { pack: 'tiny-farm', index: 113 },
  coin: { pack: 'tiny-town', index: 93 },
  sign: { pack: 'tiny-town', index: 83 },
  well: { pack: 'tiny-town', index: 104 },
  grass: { pack: 'tiny-town', index: 0 },
  'grass-tuft': { pack: 'tiny-town', index: 1 },
  'grass-flower': { pack: 'tiny-town', index: 2 },
  'tree-orange': { pack: 'tiny-town', index: 3 },
  bush: { pack: 'tiny-town', index: 5 },
  'fence-l': { pack: 'tiny-town', index: 80 },
  'fence-m': { pack: 'tiny-town', index: 81 },
  'fence-r': { pack: 'tiny-town', index: 82 },
  // M5 decorations (Collection Book)
  sunflower: { pack: 'tiny-farm', index: 83 },
  mushrooms: { pack: 'tiny-town', index: 29 },
  'berry-bush': { pack: 'tiny-farm', index: 78 },
  pine: { pack: 'tiny-farm', index: 15 },
  'apple-tree': { pack: 'tiny-town', index: 16 },
  'orange-pine': { pack: 'tiny-town', index: 27 },
  sapling: { pack: 'tiny-farm', index: 81 },
  boulder: { pack: 'tiny-farm', index: 89 },
  barrel: { pack: 'tiny-farm', index: 85 },
  'watering-can': { pack: 'tiny-farm', index: 84 },
  'hay-bale': { pack: 'tiny-farm', index: 97 },
  crate: { pack: 'tiny-farm', index: 76 },
  sack: { pack: 'tiny-farm', index: 74 },
  bucket: { pack: 'tiny-farm', index: 73 },
  target: { pack: 'tiny-town', index: 95 },
  wheelbarrow: { pack: 'tiny-town', index: 57 },
  logs: { pack: 'tiny-town', index: 106 },
};
